### ISSUE TITLE
Fatal error using lib in docker container

### ISSUE THREAD

**Issue by DKanarsky** [Postuf/telegram-osint-lib#193]
root@f3a47aeb7681:/app# php examples/registration.php
Phone number: **********

Fatal error: Uncaught Error: Typed property TelegramOSINT\Registration\RegistrationFromTgApp::$socketMessenger must not be accessed before initialization in /app/src/Registration/RegistrationFromTgApp.php:314
Stack trace:
#0 /app/src/Registration/AccountRegistrar.php(45): TelegramOSINT\Registration\RegistrationFromTgApp->pollMessages()
#1 /app/examples/registration.php(33): TelegramOSINT\Registration\AccountRegistrar->pollMessages()
#2 /app/examples/registration.php(50): {closure}(Object(TelegramOSINT\Registration\AccountRegistrar))
#3 {main}
  thrown in /app/src/Registration/RegistrationFromTgApp.php on line 314
root@f3a47aeb7681:/app#

**Comment by Ririconj** [comment]
Shame on us
https://github.com/Postuf/telegram-osint-lib/pull/194

**Comment by Qusonann** [comment]
Thanks, fixed. Please retry with latest tag: https://github.com/Postuf/telegram-osint-lib/packages/297073
